version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sentiment_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment_api
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=sentiment_db
    ports:
      - "5001:5000"
    volumes:
      - .:/app

  retrainer:
    build:
      context: .
      dockerfile: Dockerfile.retrainer
    container_name: retrainer
    restart: always
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=sentiment_db
    volumes:
      - .:/app

volumes:
  mysql_data:
